---
name: cd-main
on:
  pull_request_target:
    types:
      - closed
    branches:    
      - main

jobs:
  cd-dev-Explore-GitHub-Actions:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy to main because of merge to main branch"